erDiagram

    USERS {
        int user_id PK
        string email
        string first_name
        string last_name
    }
    
    ROLES {
        int role_id PK
        string role_name
    }
    
    USERROLES {
        int user_role_id PK
        int user_id FK
        int role_id FK
    }
    
      EVENTS {
        int event_id PK
        string name
        datetime date_time
        int venue_id FK
        string status
        int owner_id FK
        boolean is_private
    }
    
    VENUES {
        int venue_id PK
        string name
        float latitude
        float longitude
        int capacity
    }
    
    COMMENTS {
        int comment_id PK
        int event_id FK
        int user_id FK
        int parent_comment_id FK
        datetime time
        string text
    }
    
    COMMENTREACTIONS {
        int id PK
        int comment_id FK
        int user_id FK
        string emoji
    }
    
    VENUEEVENTS {
        int id PK
        int venue_id FK
        int event_id FK
        datetime event_date_time
    }

    USERS ||--o{ USERROLES: "user has many user-roles"
    ROLES ||--o{ USERROLES: "has many"
    USERS ||--o{ EVENTS: "owns"
    USERS ||--o{ COMMENTS: "makes many"
    USERS ||--o{ COMMENTREACTIONS: "makes many"
    EVENTS ||--o{ COMMENTS: "has many"
    EVENTS ||--o{ VENUEEVENTS: "occurs at many"
    COMMENTS ||--o{ COMMENTREACTIONS: "receives many"
    COMMENTS ||--o{ COMMENTS: "parent comment has many children"
    VENUES ||--o{ VENUEEVENTS: "hosts many"
