erDiagram

    USERS {
        int user_id PK
        string email
        string first_name
        string last_name
        datetime createdAt
    }
    
    ROLES {
        int role_id PK
        string role_name
        datetime createdAt
    }
    
    USERROLES {
        int user_role_id PK
        int user_id FK
        int role_id FK
        datetime createdAt
    }
    
    EVENTS {
        int event_id PK
        string name
        datetime date_time
        int venue_id FK
        string status
        int owner_id FK
        boolean is_private
        int capacity
        datetime createdAt
    }
    
    VENUES {
        int venue_id PK
        string name
        float latitude
        float longitude
        string address1
        string address2
        string postcode
        boolean is_private "only seen by owner"
        int capacity
        int owner_id FK
        datetime createdAt
    }

    INVITATIONS {
        int invitation_id PK
        int sender_id FK "leave as null for self-invite"
        int receiver_id FK
        int event_id FK
        string status
        datetime updatedAt
        datetime createdAt
    }
    
    COMMENTS {
        int comment_id PK
        int event_id FK
        int user_id FK
        int parent_comment_id FK
        datetime time
        string text
        datetime createdAt
    }
    
    REACTIONS {
        int id PK
        int comment_id FK
        int user_id FK
        string emoji
        datetime createdAt
    }

    USERS ||--o{ USERROLES: "can have many Roles"
    ROLES ||--o{ USERROLES: "can have many Users"
    USERS ||--o{ EVENTS: "owns"
    USERS ||--o{ VENUES: "owns"
    USERS ||--o{ COMMENTS: "makes many"
    USERS ||--o{ REACTIONS: "makes many"
    EVENTS ||--o{ COMMENTS: "has many"
    COMMENTS ||--o{ REACTIONS: "receives many"
    COMMENTS ||--o{ COMMENTS: "parent comment has many children"
    VENUES ||--o{ EVENTS: "hosts many"
    USERS ||--o{ INVITATIONS: "sends many"
    USERS ||--o{ INVITATIONS: "receives many"
    EVENTS ||--o{ INVITATIONS: "has many"
